# -*- coding: utf-8 -*- #
# Copyright 2026 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Command to create an agent runtime in Vertex AI."""

from googlecloudsdk.calliope import base
from googlecloudsdk.command_lib.ai.agent_runtimes import agent_runtimes_util
from googlecloudsdk.command_lib.ai.agent_runtimes import flags


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.UniverseCompatible
class Create(base.CreateCommand):
  """Create a new agent runtime.

  The agent runtime ID is generated by the service, so it cannot be chosen.

  If no source is provided, an agent runtime is created without a deployment.
  Otherwise the deployment method is inferred from the flags: `--image`
  deploys a prebuilt container, `--source` with a `Dockerfile` at its root
  builds that container, and `--source` without one deploys the Python
  application found in the source directory.

  ## EXAMPLES

  To create an agent runtime without a deployment under project ``example'' in
  region ``us-central1'', run:

    $ {command} --display-name="My agent" --project=example
    --region=us-central1

  To create an agent runtime from a prebuilt container image, run:

    $ {command} --display-name="My agent"
    --image=us-docker.pkg.dev/example/my-agent:latest --region=us-central1

  To create an agent runtime from local source code, run:

    $ {command} --display-name="My agent" --source=./my-agent
    --entrypoint-module=my_agent.agent --region=us-central1
  """

  @staticmethod
  def Args(parser):
    flags.AddCreateFlags(parser)

  def Run(self, args):
    region_ref = args.CONCEPTS.region.Parse()
    return agent_runtimes_util.CreateRuntime(
        region_ref, args, self.ReleaseTrack(), asynchronous=args.async_
    )
