# -*- coding: utf-8 -*- #
# Copyright 2024 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This file is autogenerated and should not be edited by hand.
# AUTOGEN_CLI_VERSION: HEAD
"""File to add optional custom code to extend __init__.py."""
from googlecloudsdk.calliope import base

_DEPRECATION_WARNING = """\
The `gcloud blockchain-validator` command group is deprecated and will
be removed in a future release."""


@base.DefaultUniverseOnly
@base.Deprecate(is_removed=False, warning=_DEPRECATION_WARNING)
class BlockchainValidatorAlpha(base.Group):
  """Optional no-auto-generated code for ALPHA."""
  category = base.UNCATEGORIZED_CATEGORY


@base.DefaultUniverseOnly
@base.Deprecate(is_removed=False, warning=_DEPRECATION_WARNING)
class BlockchainValidatorBeta(base.Group):
  """Optional no-auto-generated code for BETA."""
  category = base.UNCATEGORIZED_CATEGORY


@base.DefaultUniverseOnly
@base.Deprecate(is_removed=False, warning=_DEPRECATION_WARNING)
class BlockchainValidatorGa(base.Group):
  """Optional no-auto-generated code for GA."""
  category = base.UNCATEGORIZED_CATEGORY
