"""Generated message classes for dataproc version v2.

Manages Hadoop-based clusters and jobs on Google Cloud Platform.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from apitools.base.protorpclite import messages as _messages
from apitools.base.py import encoding
from apitools.base.py import extra_types


package = 'dataproc'


class DataprocProjectsLocationsEnvironmentsCreateRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsCreateRequest object.

  Fields:
    environment: A Environment resource to be passed as the request body.
    environmentId: Required. The ID to use for the environment, which becomes
      the final component of the environment's resource name.
    parent: Required. The parent resource where this environment will be
      created.
    requestId: Optional. A unique ID used to identify the request. If the
      service receives two CreateEnvironmentRequests with the same ID, the
      second request is ignored, and the first environment is created and
      stored in the backend.Recommendation: Set this value to a UUID
      (https://en.wikipedia.org/wiki/Universally_unique_identifier).The value
      must be a valid UUID as defined by RFC 4122.
  """

  environment = _messages.MessageField('Environment', 1)
  environmentId = _messages.StringField(2)
  parent = _messages.StringField(3, required=True)
  requestId = _messages.StringField(4)


class DataprocProjectsLocationsEnvironmentsDeleteRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsDeleteRequest object.

  Fields:
    etag: Optional. The current etag of the environment. If provided, the
      delete is only performed if the etag matches the environment's current
      etag; otherwise the request fails with an ABORTED error. This lets
      clients avoid deleting an environment that has changed since they last
      read it. See https://google.aip.dev/154 for more information.
    name: Required. The name of the environment resource to delete.
    requestId: Optional. A unique ID used to identify the request. If the
      service receives two DeleteEnvironmentRequests with the same ID, the
      second request is ignored.The value must be a valid UUID as defined by
      RFC 4122.
  """

  etag = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  requestId = _messages.StringField(3)


class DataprocProjectsLocationsEnvironmentsGetRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsGetRequest object.

  Fields:
    name: Required. The name of the environment to retrieve. Format:
      projects/{project}/locations/{location}/environments/{environment}This
      returns the latest revision of the environment. To retrieve a specific
      historical revision, use ListEnvironmentRevisions or get the
      EnvironmentRevision resource directly
      (.../environments/{environment}/revisions/{revision}).
  """

  name = _messages.StringField(1, required=True)


class DataprocProjectsLocationsEnvironmentsListRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsListRequest object.

  Fields:
    filter: Optional. A filter for the environments to return in the
      response.See https://google.aip.dev/160 for a detailed description of
      the filter syntax.
    orderBy: Optional. Field(s) on which to sort the list of environments. See
      https://google.aip.dev/132#ordering for more information.
    pageSize: Optional. The maximum number of environments to return in each
      response. The service may return fewer than this value.The default page
      size is 20; the maximum page size is 1000. Values above 1000 are coerced
      to 1000.
    pageToken: Optional. A page token received from a previous
      ListEnvironments call. Provide this token to retrieve the subsequent
      page.
    parent: Required. The parent, which owns this collection of environments.
  """

  filter = _messages.StringField(1)
  orderBy = _messages.StringField(2)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)
  parent = _messages.StringField(5, required=True)


class DataprocProjectsLocationsEnvironmentsPatchRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsPatchRequest object.

  Fields:
    environment: A Environment resource to be passed as the request body.
    name: Identifier. The resource name of the environment. Format:
      projects/{project}/locations/{location}/environments/{environment}
    requestId: Optional. A unique ID used to identify the request. If the
      service receives two UpdateEnvironmentRequests with the same ID, the
      second request is ignored.The value must be a valid UUID as defined by
      RFC 4122.
    updateMask: Optional. The list of fields to update.
  """

  environment = _messages.MessageField('Environment', 1)
  name = _messages.StringField(2, required=True)
  requestId = _messages.StringField(3)
  updateMask = _messages.StringField(4)


class DataprocProjectsLocationsEnvironmentsRevisionsDeleteRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsRevisionsDeleteRequest object.

  Fields:
    name: Required. The name of the environment revision to delete. Format: pr
      ojects/{project}/locations/{location}/environments/{environment}/revisio
      ns/{revision}
    requestId: Optional. A unique ID used to identify the request. If the
      service receives two DeleteEnvironmentRevisionRequests with the same ID,
      the second request is ignored.
  """

  name = _messages.StringField(1, required=True)
  requestId = _messages.StringField(2)


class DataprocProjectsLocationsEnvironmentsRevisionsGetRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsRevisionsGetRequest object.

  Fields:
    name: Required. The name of the environment revision to retrieve. Format:
      projects/{project}/locations/{location}/environments/{environment}/revis
      ions/{revision}
  """

  name = _messages.StringField(1, required=True)


class DataprocProjectsLocationsEnvironmentsRevisionsListRequest(_messages.Message):
  r"""A DataprocProjectsLocationsEnvironmentsRevisionsListRequest object.

  Fields:
    filter: Optional. A filter for the environment revisions to return in the
      response.See https://google.aip.dev/160 for a detailed description of
      the filter syntax.
    pageSize: Optional. The maximum number of revisions to return in each
      response. The service may return fewer than this value.The default page
      size is 20; the maximum page size is 1000. Values above 1000 are coerced
      to 1000.
    pageToken: Optional. A page token received from a previous
      ListEnvironmentRevisions call. Provide this token to retrieve the
      subsequent page.
    parent: Required. The parent environment whose revisions should be listed.
  """

  filter = _messages.StringField(1)
  pageSize = _messages.IntegerField(2, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(3)
  parent = _messages.StringField(4, required=True)


class DataprocProjectsLocationsOperationsCancelRequest(_messages.Message):
  r"""A DataprocProjectsLocationsOperationsCancelRequest object.

  Fields:
    name: The name of the operation resource to be cancelled.
  """

  name = _messages.StringField(1, required=True)


class DataprocProjectsLocationsOperationsDeleteRequest(_messages.Message):
  r"""A DataprocProjectsLocationsOperationsDeleteRequest object.

  Fields:
    name: The name of the operation resource to be deleted.
  """

  name = _messages.StringField(1, required=True)


class DataprocProjectsLocationsOperationsGetRequest(_messages.Message):
  r"""A DataprocProjectsLocationsOperationsGetRequest object.

  Fields:
    name: The name of the operation resource.
  """

  name = _messages.StringField(1, required=True)


class DataprocProjectsLocationsOperationsListRequest(_messages.Message):
  r"""A DataprocProjectsLocationsOperationsListRequest object.

  Fields:
    filter: The standard list filter.
    name: The name of the operation's parent resource.
    pageSize: The standard list page size.
    pageToken: The standard list page token.
    returnPartialSuccess: When set to true, operations that are reachable are
      returned as normal, and those that are unreachable are returned in the
      ListOperationsResponse.unreachable field.This can only be true when
      reading across collections. For example, when parent is set to
      "projects/example/locations/-".This field is not supported by default
      and will result in an UNIMPLEMENTED error if set unless explicitly
      documented otherwise in service or product specific documentation.
  """

  filter = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)
  returnPartialSuccess = _messages.BooleanField(5)


class Empty(_messages.Message):
  r"""A generic empty message that you can re-use to avoid defining duplicated
  empty messages in your APIs. A typical example is to use it as the request
  or the response type of an API method. For instance: service Foo { rpc
  Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }
  """



class Environment(_messages.Message):
  r"""An Environment represents a managed Spark execution
  environment.Following the API Improvement Proposal for resource revisions
  (https://google.aip.dev/162), each Environment has a history of immutable
  EnvironmentRevisions. When a user updates the environment's dependencies,
  the Dataproc Control Plane automatically generates a new, immutable
  revision.

  Enums:
    StateValueValuesEnum: Output only. The state of the environment revision
      build.

  Messages:
    LabelsValue: Optional. User-defined labels for the environment.

  Fields:
    baseEnvironment: Optional. The resource name of an existing environment to
      build upon. Format:
      projects/{project}/locations/{location}/environments/{environment}
    baseVersion: Optional. The Dataproc predefined base environment version to
      build upon (for example, 1.0 or 2.0), which contains a specific Python
      interpreter and standard libraries.
    createTime: Output only. The time when the environment was created.
    description: Optional. Human-readable description of the environment.
    etag: Optional. An opaque, server-generated checksum of the environment's
      contents. Clients may send it on update and delete requests to ensure
      they are acting on the latest version, avoiding race conditions. See
      https://google.aip.dev/154 for more information.
    labels: Optional. User-defined labels for the environment.
    name: Identifier. The resource name of the environment. Format:
      projects/{project}/locations/{location}/environments/{environment}
    pythonPackagesConfig: Optional. Configuration for Python packages to
      install in the environment.
    revisionId: Output only. The globally unique, system-generated revision ID
      of the environment. This is updated every time the environment is
      successfully built.
    state: Output only. The state of the environment revision build.
    status: Output only. Output only. Detailed status of the current
      environment revision.
    uid: Output only. The unique identifier for the environment. The service
      generates this value when it creates the environment.
    updateTime: Output only. The time when the environment was last updated.
  """

  class StateValueValuesEnum(_messages.Enum):
    r"""Output only. The state of the environment revision build.

    Values:
      STATE_UNSPECIFIED: The environment state is unknown.
      CREATING: The environment's dependencies are being compiled and
        installed.
      ACTIVE: The environment's assets are built and it is ready to be used by
        workloads.
      FAILED: Creation of the environment failed. The failure reason is
        reported on the operation's error. Failures during an update are
        reported on the operation and leave the environment in ACTIVE.
      DELETING: The environment's assets are being deleted and the environment
        is being removed.
    """
    STATE_UNSPECIFIED = 0
    CREATING = 1
    ACTIVE = 2
    FAILED = 3
    DELETING = 4

  @encoding.MapUnrecognizedFields('additionalProperties')
  class LabelsValue(_messages.Message):
    r"""Optional. User-defined labels for the environment.

    Messages:
      AdditionalProperty: An additional property for a LabelsValue object.

    Fields:
      additionalProperties: Additional properties of type LabelsValue
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a LabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  baseEnvironment = _messages.StringField(1)
  baseVersion = _messages.StringField(2)
  createTime = _messages.StringField(3)
  description = _messages.StringField(4)
  etag = _messages.StringField(5)
  labels = _messages.MessageField('LabelsValue', 6)
  name = _messages.StringField(7)
  pythonPackagesConfig = _messages.MessageField('PythonPackagesConfig', 8)
  revisionId = _messages.StringField(9)
  state = _messages.EnumField('StateValueValuesEnum', 10)
  status = _messages.MessageField('EnvironmentStatus', 11)
  uid = _messages.StringField(12)
  updateTime = _messages.StringField(13)


class EnvironmentRevision(_messages.Message):
  r"""An immutable, point-in-time snapshot of an Environment. Following
  https://google.aip.dev/162, each successful compilation of an Environment
  produces a new EnvironmentRevision.

  Fields:
    createTime: Output only. The time when this revision was created.
    environment: Output only. A point-in-time snapshot of the environment at
      this revision.
    name: Identifier. The resource name of the environment revision. Format: p
      rojects/{project}/locations/{location}/environments/{environment}/revisi
      ons/{revision}
  """

  createTime = _messages.StringField(1)
  environment = _messages.MessageField('Environment', 2)
  name = _messages.StringField(3)


class EnvironmentStatus(_messages.Message):
  r"""Detailed status of an environment revision.

  Fields:
    baseVersion: Output only. The resolved base environment version. Populated
      even when the customer built on top of a custom base_environment.
  """

  baseVersion = _messages.StringField(1)


class ListEnvironmentRevisionsResponse(_messages.Message):
  r"""A list of environment revisions.

  Fields:
    environmentRevisions: The revisions of the environment.
    nextPageToken: A token, which can be sent as page_token, to retrieve the
      next page. If this field is omitted, there are no subsequent pages.
  """

  environmentRevisions = _messages.MessageField('EnvironmentRevision', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListEnvironmentsResponse(_messages.Message):
  r"""A list of environments.

  Fields:
    environments: The environments from the specified collection.
    nextPageToken: A token, which can be sent as page_token, to retrieve the
      next page. If this field is omitted, there are no subsequent pages.
  """

  environments = _messages.MessageField('Environment', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListOperationsResponse(_messages.Message):
  r"""The response message for Operations.ListOperations.

  Fields:
    nextPageToken: The standard List next-page token.
    operations: A list of operations that matches the specified filter in the
      request.
    unreachable: Unordered list. Unreachable resources. Populated when the
      request sets ListOperationsRequest.return_partial_success and reads
      across collections. For example, when attempting to list all resources
      across all supported locations.
  """

  nextPageToken = _messages.StringField(1)
  operations = _messages.MessageField('Operation', 2, repeated=True)
  unreachable = _messages.StringField(3, repeated=True)


class Operation(_messages.Message):
  r"""This resource represents a long-running operation that is the result of
  a network API call.

  Messages:
    MetadataValue: Service-specific metadata associated with the operation. It
      typically contains progress information and common metadata such as
      create time. Some services might not provide such metadata. Any method
      that returns a long-running operation should document the metadata type,
      if any.
    ResponseValue: The normal, successful response of the operation. If the
      original method returns no data on success, such as Delete, the response
      is google.protobuf.Empty. If the original method is standard
      Get/Create/Update, the response should be the resource. For other
      methods, the response should have the type XxxResponse, where Xxx is the
      original method name. For example, if the original method name is
      TakeSnapshot(), the inferred response type is TakeSnapshotResponse.

  Fields:
    done: If the value is false, it means the operation is still in progress.
      If true, the operation is completed, and either error or response is
      available.
    error: The error result of the operation in case of failure or
      cancellation.
    metadata: Service-specific metadata associated with the operation. It
      typically contains progress information and common metadata such as
      create time. Some services might not provide such metadata. Any method
      that returns a long-running operation should document the metadata type,
      if any.
    name: The server-assigned name, which is only unique within the same
      service that originally returns it. If you use the default HTTP mapping,
      the name should be a resource name ending with operations/{unique_id}.
    response: The normal, successful response of the operation. If the
      original method returns no data on success, such as Delete, the response
      is google.protobuf.Empty. If the original method is standard
      Get/Create/Update, the response should be the resource. For other
      methods, the response should have the type XxxResponse, where Xxx is the
      original method name. For example, if the original method name is
      TakeSnapshot(), the inferred response type is TakeSnapshotResponse.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    r"""Service-specific metadata associated with the operation. It typically
    contains progress information and common metadata such as create time.
    Some services might not provide such metadata. Any method that returns a
    long-running operation should document the metadata type, if any.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ResponseValue(_messages.Message):
    r"""The normal, successful response of the operation. If the original
    method returns no data on success, such as Delete, the response is
    google.protobuf.Empty. If the original method is standard
    Get/Create/Update, the response should be the resource. For other methods,
    the response should have the type XxxResponse, where Xxx is the original
    method name. For example, if the original method name is TakeSnapshot(),
    the inferred response type is TakeSnapshotResponse.

    Messages:
      AdditionalProperty: An additional property for a ResponseValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a ResponseValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  done = _messages.BooleanField(1)
  error = _messages.MessageField('Status', 2)
  metadata = _messages.MessageField('MetadataValue', 3)
  name = _messages.StringField(4)
  response = _messages.MessageField('ResponseValue', 5)


class OperationMetadata(_messages.Message):
  r"""Represents the metadata of a long-running operation.

  Fields:
    apiVersion: Output only. API version used to start the operation.
    createTime: Output only. The time the operation was created.
    endTime: Output only. The time the operation finished running.
    requestedCancellation: Output only. Identifies whether the user has
      requested cancellation of the operation. Operations that have been
      cancelled successfully have Operation.error with a
      google.rpc.Status.code of 1, corresponding to Code.CANCELLED.
    statusMessage: Output only. Human-readable status of the operation, if
      any.
    target: Output only. Server-defined resource path for the target of the
      operation.
    verb: Output only. Name of the verb executed by the operation.
  """

  apiVersion = _messages.StringField(1)
  createTime = _messages.StringField(2)
  endTime = _messages.StringField(3)
  requestedCancellation = _messages.BooleanField(4)
  statusMessage = _messages.StringField(5)
  target = _messages.StringField(6)
  verb = _messages.StringField(7)


class PythonPackagesConfig(_messages.Message):
  r"""Configuration for Python packages installed in an environment, resolved
  and installed with pip from the public PyPI index.

  Fields:
    packages: Optional. Python packages to install, specified as pip
      requirement strings (for example, pandas>=2.0.0 or scipy).
  """

  packages = _messages.StringField(1, repeated=True)


class StandardQueryParameters(_messages.Message):
  r"""Query parameters accepted by all methods.

  Enums:
    FXgafvValueValuesEnum: V1 error format.
    AltValueValuesEnum: Data format for response.

  Fields:
    f__xgafv: V1 error format.
    access_token: OAuth access token.
    alt: Data format for response.
    callback: JSONP
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters.
    trace: A tracing token of the form "token:<tokenid>" to include in api
      requests.
    uploadType: Legacy upload protocol for media (e.g. "media", "multipart").
    upload_protocol: Upload protocol for media (e.g. "raw", "multipart").
  """

  class AltValueValuesEnum(_messages.Enum):
    r"""Data format for response.

    Values:
      json: Responses with Content-Type of application/json
      media: Media download with context-dependent Content-Type
      proto: Responses with Content-Type of application/x-protobuf
    """
    json = 0
    media = 1
    proto = 2

  class FXgafvValueValuesEnum(_messages.Enum):
    r"""V1 error format.

    Values:
      _1: v1 error format
      _2: v2 error format
    """
    _1 = 0
    _2 = 1

  f__xgafv = _messages.EnumField('FXgafvValueValuesEnum', 1)
  access_token = _messages.StringField(2)
  alt = _messages.EnumField('AltValueValuesEnum', 3, default='json')
  callback = _messages.StringField(4)
  fields = _messages.StringField(5)
  key = _messages.StringField(6)
  oauth_token = _messages.StringField(7)
  prettyPrint = _messages.BooleanField(8, default=True)
  quotaUser = _messages.StringField(9)
  trace = _messages.StringField(10)
  uploadType = _messages.StringField(11)
  upload_protocol = _messages.StringField(12)


class Status(_messages.Message):
  r"""The Status type defines a logical error model that is suitable for
  different programming environments, including REST APIs and RPC APIs. It is
  used by gRPC (https://github.com/grpc). Each Status message contains three
  pieces of data: error code, error message, and error details.You can find
  out more about this error model and how to work with it in the API Design
  Guide (https://cloud.google.com/apis/design/errors).

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: The status code, which should be an enum value of google.rpc.Code.
    details: A list of messages that carry the error details. There is a
      common set of message types for APIs to use.
    message: A developer-facing error message, which should be in English. Any
      user-facing error message should be localized and sent in the
      google.rpc.Status.details field, or localized by the client.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(_messages.Message):
    r"""A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  details = _messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = _messages.StringField(3)


encoding.AddCustomJsonFieldMapping(
    StandardQueryParameters, 'f__xgafv', '$.xgafv')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_1', '1')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_2', '2')
